### ISSUE TITLE
Describe steps how to configure and run github application locally (preferably in a form of shell script)

### ISSUE THREAD

**Issue by ChShersh** [kowainik/hintman#6]
Documentation for building APP:

* https://developer.github.com/apps/building-your-first-github-app/#start-a-new-smee-channel

I would like to have instructions how to configure environment before running application. Better in a form of shell script. So in terminal everyone can just:

```shell
$ ./setup-app-env.sh
$ cabal new-exec hintman  # or `stack exec hintman`
```

If something is required to do manually, this should be specified in the README.md file.

**Comment by kahlil29** [comment]
The Github App needs `npm` and `ruby` to be installed in order to run `smee` and to get webhook notifications from `smee` on localhost port. 
I am assuming you want these 2 to be installed (if not already installed) on the user's machine? (via the script)

@ChShersh I wanted to clarify with you that this shell script will be for developers to run on their machines in order to develop and test the App ? 

I have gone through the flow of creating a new GitHub app and made a note of things that would need to be done (including those that would need manual intervention). 
I haven't worked with shell scripts for a long time and I haven't written any non-trivial script before so I may ask you for some help when I attempt that.

**Comment by ChShersh** [comment]
@kahlil29 Yes, the instructions are for the developers. And partially for executing on server that will host this GitHub App.

Regarding shell script: it shouldn't be interactive. I assume that there will be commands like:

```shell
export GITHUB_PRIVATE_KEY= ...
```

So later we just need to insert values for those commands to prepare environment.
